version: '2.0'

services:
  application:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8081:8081
    tty: true
    volumes:
      - ./lang/:/app